services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  sidekiq-7.3:
    build:
      context: .
      args:
        BUNDLE_GEMFILE: Gemfile.sidekiq-7.3
    depends_on:
      redis:
        condition: service_healthy
    environment:
      REDIS_URL: redis://redis:6379/0
    ports:
      - "9292:9292"
    volumes:
      - .:/app

  sidekiq-8.0:
    build:
      context: .
      args:
        BUNDLE_GEMFILE: Gemfile.sidekiq-8.0
    depends_on:
      redis:
        condition: service_healthy
    environment:
      REDIS_URL: redis://redis:6379/1
    ports:
      - "9293:9292"
    volumes:
      - .:/app

  sidekiq-8.1:
    build:
      context: .
      args:
        BUNDLE_GEMFILE: Gemfile.sidekiq-8.1
    depends_on:
      redis:
        condition: service_healthy
    environment:
      REDIS_URL: redis://redis:6379/2
    ports:
      - "9294:9292"
    volumes:
      - .:/app
